# -*- coding: utf-8 -*-
"""Pitchingperformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btNkD8CLDKEgN0222FCD3njZaiM73Fq9

📊 Baseball Pitching Analysis — Overview

This project analyzes MLB pitching data using Statcast to identify pitcher tendencies and classify pitching styles based on fastball velocity and usage. Using a sample dataset, we extract key variables such as pitch type, release speed, and outcomes, then engineer features to measure average fastball velocity and fastball usage percentage for each pitcher.

Pitchers are grouped into archetypes—Power Fastball, Offspeed Heavy, and Balanced—to simplify interpretation and highlight strategic differences in approach. This framework allows for scalable analysis across different time periods, enabling deeper insights into how pitching profiles evolve over a season.

The workflow follows a structured pipeline: data extraction, cleaning, feature engineering, aggregation, and classification, ensuring results are both interpretable and extensible for further analysis.

Imports
-pybaseball pip install *
-pandas
-numpy
"""

from pybaseball import statcast
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

"""TEST DATA PULL (Small Range)"""

data = statcast(start_dt="2024-04-01", end_dt="2024-04-07")

print(data.shape)
data.head()

"""Keep Only What We Need"""

df = data[[
     'player_name',
    'game_date',
    'pitch_type',
    'release_speed',
    'events'


]].dropna()
df.sort_values(by='player_name', ascending=False)

"""Define Fastball Types"""

fastballs = ['FF', 'SI', 'FC', 'FT']

"""Define OUT Events"""

outs = ['field_out', 'groundout', 'flyout', 'lineout']

df['is_out'] = df['events'].isin(outs).astype(int)

"""Calculate Pitcher Stats"""

fastball_data = df[df['pitch_type'].isin(fastballs)]
velo = fastball_data.groupby('player_name')['release_speed'].mean().reset_index()
velo.columns = ['player_name', 'avg_fastball_velo']

"""Calculate pitcher Stats"""

pitcher_stats = df.groupby('player_name').agg({
    'is_out': 'mean',
    'release_speed': 'mean',
    'pitch_type': lambda x: x.isin(fastballs).mean()
}).reset_index()

pitcher_stats.rename(columns={
    'is_out': 'Out Rate'
}, inplace=True)

"""Fastball usage %"""

total_pitches = df.groupby('player_name').size().reset_index(name='total_pitches')

fastball_counts = fastball_data.groupby('player_name').size().reset_index(name='fastball_count')

usage = pd.merge(total_pitches, fastball_counts, on='player_name', how='left').fillna(0)

usage['fastball_pct'] = usage['fastball_count'] / usage['total_pitches']
usage.sort_values(by='fastball_pct', ascending=False)

"""Combine Them"""

pitcher_stats = pd.merge(velo, usage, on='player_name')
pitcher_stats.sort_values(by='avg_fastball_velo', ascending=False)

"""Classify Pitchers"""

def classify_pitcher(row):
    if row['avg_fastball_velo'] >= 95 and row['fastball_pct'] >= 0.55:
        return 'Power Fastball'
    elif row['fastball_pct'] <= 0.45:
        return 'Offspeed Heavy'
    else:
        return 'Balanced'

pitcher_stats['archetype'] = pitcher_stats.apply(classify_pitcher, axis=1)

"""QUICK CHECK"""

pitcher_stats.head()
pitcher_stats['archetype'].value_counts()

"""Create outcome columns

"""

df['is_hit'] = df['events'].isin(['single', 'double', 'triple', 'home_run']).astype(int)
df['is_strikeout'] = (df['events'] == 'strikeout').astype(int)
outs = [
    'field_out', 'force_out', 'grounded_into_double_play',
    'double_play', 'fielders_choice_out',
    'sac_fly', 'sac_bunt'
]

df['is_out'] = df['events'].isin(outs).astype(int)

"""AGG performance Per Pitcher"""

performance = df.groupby('player_name').agg({
    'is_hit': 'sum',
    'is_strikeout': 'sum',
    'is_out': 'sum',
    'events': 'count'
}).reset_index()

performance.columns = ['player_name', 'hits', 'strikeouts', 'outs', 'total_events']

"""Create Rates K rate Hit rate"""

performance['hit_rate'] = performance['hits'] / performance['total_events']
performance['k_rate'] = performance['strikeouts'] / performance['total_events']
performance['out_minus_hit'] = performance['outs'] - performance['hits']
performance['run_prevention'] = performance['out_minus_hit'] / performance['total_events']
performance['out_rate'] = performance['outs'] / performance['total_events']
performance['run_prevention'] = (performance['outs'] - performance['hits']) / performance['total_events']

"""Contact Quality Aggregation Damage Rate"""

performance['damage_rate'] = performance['hits'] / performance['total_events']

"""ADD TIME (SEASON SPLIT)"""

df['game_date'] = pd.to_datetime(df['game_date'])
df['month'] = df['game_date'].dt.month

"""Merge Performance"""

final_df = pd.merge(pitcher_stats, performance, on='player_name')
final_df.groupby('archetype')[['k_rate','hit_rate','out_rate']].mean()

final_df.info()

"""Define Season Buckets"""

def season_period(month):
    if month <= 5:
        return 'Early'
    elif month <= 7:
        return 'Mid'
    else:
        return 'Late'

df['season_period'] = df['month'].apply(season_period)

"""Plot"""

plt.scatter(final_df['avg_fastball_velo'], final_df['k_rate'])
plt.xlabel('Fastball Velocity')
plt.ylabel('Strikeout Rate')
plt.title('Velocity vs Strikeouts')
plt.show()

"""prep and download  cleanedfiles"""

final_df.to_csv('pitching_analysis.csv', index=False)
files.download('pitching_analysis.csv')